name: mala_front
description: A new Flutter project.
publish_to: 'none'
version: 1.1.1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  archive: ^3.3.8
  auto_size_text: ^3.0.0
  awesome_flutter_extensions: ^1.1.1
  badges: ^3.1.2
  brasil_fields: ^1.14.0
  camera: ^0.10.5+9
  camera_universal: ^0.0.3
  dio: ^5.3.2
  file_picker: ^5.5.0
  fluent_ui: ^4.7.3
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  mask_text_input_formatter: ^2.8.0
  package_info_plus: ^4.2.0
  path_provider: ^2.1.0
  pdf: ^3.10.4
  printing: ^5.11.0
  search_cep: ^4.0.2
  shared_preferences: ^2.2.1
  vit:
    git:
      url: https://gitlab.com/vit16/vit_dart_extensions.git
  wave: ^0.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/logo-icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  windows:
    generate: true
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true