name: mala_front
description: A new Flutter project.
publish_to: 'none'
version: 1.4.1+10

environment:
  sdk: '>=3.10.1 <4.0.0'

dependencies:
  auto_size_text: ^3.0.0
  awesome_flutter_extensions: ^2.0.1
  badges: ^3.1.2
  brasil_fields: ^1.14.0
  camera: ^0.10.5+9
  camera_universal:
    git:
      url: https://github.com/TimeLord2010/camera_universal.git
  dio: ^5.3.2
  fluent_ui: ^4.13.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  get_it: ^9.0.0
  mask: ^1.0.5
  mask_text_input_formatter: ^2.8.0
  package_info_plus: ^4.2.0
  path_provider: ^2.1.0
  permission_handler: ^12.0.1
  provider: ^6.1.2
  shared_preferences: ^2.2.1
  system_info2: ^4.0.0
  vit_logger: ^2.0.1
  wave: ^0.2.2
  mala_api:
    path: ../mala_api
  image_compression: ^1.0.5
  file_picker: ^8.3.3
  gap: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_launcher_icons:
  android: 'launcher_icon'
  ios: false
  image_path: 'assets/logo-icon.png'
  min_sdk_android: 21 # android min sdk min:16, default 21
  windows:
    generate: true
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
